### ISSUE TITLE
Program crashes on windos 7

### ISSUE THREAD

**Issue by ak83** [ak83/MCTS#108]
When run, program crashes on windows 7 with following stack strace:

java.io.IOException: Couldn't get lock for /test.log
    at java.util.logging.FileHandler.openFiles(Unknown Source)
    at java.util.logging.FileHandler.<init>(Unknown Source)
    at logging.Logs.initLoggers(Logs.java:46)
    at start.Main.main(Main.java:37)

**Comment by ak83** [comment]
hours worked: 1.5
